### ISSUE TITLE
Upgrade to Spout 3.0 ?

### ISSUE THREAD

**Issue by johanrosenson** [rap2hpoutre/fast-excel#142]
Spout version 3 is available, would it be possible to upgrade to use that version instead of 2.7?

According to the upgrade guide there are some breaking changes between 2.7 and 3.0
https://github.com/box/spout/blob/master/UPGRADE-3.0.md

I have not done any tests myself yet, but creating an issue if someone wants to try (or if i get time soon to do some tests).

**Comment by oriceon** [comment]
Hi there, any news regarding that?

**Comment by rap2hpoutre** [comment]
It should be considered. Still, I read the updgrade documentation and it seems it's not that simple. We would have to adapt some code, adapt tests, and check benchmark again (since [creating a new row ](https://github.com/box/spout/blob/master/UPGRADE-3.0.md#reader-changes) for each read line could consume some more memory and time).

**Comment by rap2hpoutre** [comment]
I just updated fast-excel to use Spout v3. Could you try to install the v3.0.0: composer require rap2hpoutre/fast-excel:^3? Let me know if it fixes your issue.
