### ISSUE TITLE
failed to open stream:

### ISSUE THREAD

**Issue by bkvishe** [rap2hpoutre/fast-excel#145]
Getting below error while  exporting  data.

**Permission denied in /var/www/html/#project#/vendor/box/spout/src/Spout/Common/Helper/GlobalFunctionsHelper.php:25**

Could I know  the location where files get stored while exporting ?

**Comment by rap2hpoutre** [comment]
Hi @bkvishe ! Thank you for your feedback and sorry for late answer. This issue is not easy to debug since it depends on spout and your system. 

You could have a look at these issues:
 - https://github.com/rap2hpoutre/fast-excel/issues/18
 - https://github.com/rap2hpoutre/fast-excel/issues/57
 - https://github.com/rap2hpoutre/fast-excel/issues/53

Hope it could help. Also could you share the code that does not work?
