### ISSUE TITLE
Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by xlight** [rap2hpoutre/fast-excel#192]
```
local.ERROR: Class 'ZipArchive' not found {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'ZipArchive' not found at /data/NingSamples/vendor/box/spout/src/Spout/Writer/Common/Helper/ZipHelper.php:78)
```

please declare require ext-zip in composer.json

**Comment by rap2hpoutre** [comment]
Hi @xlight 👋 Thank you for your feedback.

Since [Spout](https://github.com/box/spout) (which is the lib on which this package is based) already declares `ext-zip` as mandatory [here](https://github.com/box/spout/blob/0f0bf648024040d21c6bd9930299265e8fc42550/composer.json#L16), I guess we should not add it to this package repository (as far as I know dependencies are transitive). Maybe I missed something though, feel free to comment!
