### ISSUE TITLE
Could not open file for reading

### ISSUE THREAD

**Issue by introwit** [rap2hpoutre/fast-excel#57]
## The code being used

```php
(new FastExcel)
        ->import($request->file('csv'))
        ->map(function ($item, $key) {
...
```

## The exception

```
IOException {#737
  #message: "Could not open /private/var/tmp/phpHjZSi4 for reading! (Could not open /private/var/tmp/phpHjZSi4 for reading.)"
  #code: 0
  #file: "/Users/harish/code/client/studio/vendor/box/spout/src/Spout/Reader/AbstractReader.php"
  #line: 126
  trace: {
    /Users/harish/code/client/studio/vendor/box/spout/src/Spout/Reader/AbstractReader.php:126 {}
    /Users/harish/code/client/studio/vendor/rap2hpoutre/fast-excel/src/Importable.php:96 {}
    /Users/harish/code/client/studio/vendor/rap2hpoutre/fast-excel/src/Importable.php:47 {}
    /Users/harish/code/client/studio/app/Repositories/StationInviteRepository.php:43 {
      › (new FastExcel)
      ›     ->import($request->file('csv'))
      ›     ->map(function ($item, $key) {
      arguments: {
        $path: UploadedFile {#480 …}
      }
    }
```

Already tried saving it first to the local disk and then using `Storage::get()`, still the problem persists.

**Comment by ankurk91** [comment]
Does it belongs to
https://github.com/rap2hpoutre/fast-excel/issues/53

**Comment by ankurk91** [comment]
fast-excel is using spout php library under the hood.
You might want try out that

http://opensource.box.com/spout/

**Comment by rap2hpoutre** [comment]
@introwit Hi and thank you for your contribution! (and sorry for late answer, happy to see you again!) Could you send a minimal example of a CSV that does not work? I could try to import it and see if something is wrong. Still I'm not sure it's a problem about the file itself, I feel more it's a problem of permission due to Spout. Did you found an issue similar to yours on the spout repository?

@ankurk91 Thank for your help on this ticket!
